 // openAnimatedModalButton.show(!this.showAnimatedModal),
        // text("foobar"),
        // div({style: {width: "100px", height: "100px", backgroundColor: adjustLightness(color, -0.2)}}),
        // div({style: {width: "100px", height: "100px", backgroundColor: adjustLightness(color, -0.1)}}),
        // div({style: {width: "100px", height: "100px", backgroundColor: color}}),
        // div({style: {width: "100px", height: "100px", backgroundColor: adjustLightness(color, 0.1)}}),
        // div({style: {width: "100px", height: "100px", backgroundColor: adjustLightness(color, 0.2)}}),
        // div({style: {width: "100px", height: "100px", backgroundColor: adjustLightness(color, 0.3)}}),
        // div({style: {width: "100px", height: "100px", backgroundColor: adjustLightness(color, 0.4)}}),
        // div({style: {width: "100px", height: "100px", backgroundColor: adjustLightness(color, 0.5)}}),
        // div({style: {width: "100px", height: "100px", backgroundColor: adjustLightness(color, 0.6)}}),